# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# carregar o dataset a partir do arquivo local
file_path = 'world_alcohol.csv'
df = pd.read_csv(file_path)

# a) agrupar os dados por tipo de bebidas
grupo_bebidas = df.groupby('Beverage Types')

# b) agrupar os dados por Região e por Ano
grupo_regiao_ano = df.groupby(['WHO region', 'Year'])

# c) seção de Contagens
contagem_regioes = df['WHO region'].value_counts()
contagem_paises = df['Country'].nunique()
soma_valores_bebida = grupo_bebidas['Display Value'].sum()

# d) análises estatísticas da coluna dos valores
media_valores_bebida = grupo_bebidas['Display Value'].mean()
moda_valores_bebida = grupo_bebidas['Display Value'].agg(pd.Series.mode)
mediana_valores_bebida = grupo_bebidas['Display Value'].median()
estatisticas_descritivas_valores_bebida = grupo_bebidas['Display Value'].describe()

# e) resultados de acordo com alguns critérios
crit1 = df[df['Year'] == 1985]['Beverage Types']
crit2 = df['WHO region'].value_counts() > 4

# resultados
print("a) agrupamento por tipo de bebida:")
print(grupo_bebidas.head(5))

print("\nb) agrupamento por Região e por Ano:")
print(grupo_regiao_ano.head(5))

print("\nc) seção de Contagens:")
print("contagem de Regiões:\n", contagem_regioes)
print("contagem de Países:", contagem_paises)
print("soma dos valores por Bebida:\n", soma_valores_bebida)

print("\nd) análises estatísticas da coluna dos valores:")
print("média dos valores por Bebida:\n", media_valores_bebida)
print("moda dos valores por Bebida:\n", moda_valores_bebida)
print("mediana dos valores por Bebida:\n", mediana_valores_bebida)
print("estatísticas Descritivas dos valores por Bebida:\n", estatisticas_descritivas_valores_bebida)

print("\ne) resultados de acordo com alguns critérios:")
print("i) coluna de bebidas do ano de 1985:\n", crit1)
print("ii) coluna de Região com valores acima de 4:\n", crit2)